In [3]:
from sklearn.datasets import load_iris
iris = load_iris()
print(type(iris))

<class 'sklearn.utils._bunch.Bunch'>


In [4]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [7]:
print(iris.data.shape)
iris.data


(150, 4)


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [9]:
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [11]:
import pandas as pd
df = pd.DataFrame(
    iris['data'],
    columns=iris['feature_names']
)
df['품종'] = iris['target']
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  품종
0                5.1               3.5                1.4               0.2   0
1                4.9               3.0                1.4               0.2   0
2                4.7               3.2                1.3               0.2   0
3                4.6               3.1                1.5               0.2   0
4                5.0               3.6                1.4               0.2   0

In [12]:
df['품종2'] = df['품종'].apply(lambda i : iris['target_names'][i])
df.head()

sepal length (cm)  sepal width (cm)  ...  품종     품종2
0                5.1               3.5  ...   0  setosa
1                4.9               3.0  ...   0  setosa
2                4.7               3.2  ...   0  setosa
3                4.6               3.1  ...   0  setosa
4                5.0               3.6  ...   0  setosa

[5 rows x 6 columns]

In [13]:
df[(df['sepal length (cm)']==5)&(df['sepal width (cm)']==3.5)]

sepal length (cm)  sepal width (cm)  ...  품종     품종2
40                5.0               3.5  ...   0  setosa
43                5.0               3.5  ...   0  setosa

[2 rows x 6 columns]

In [14]:
from sklearn.tree import DecisionTreeClassifier

In [15]:
model = DecisionTreeClassifier()
model

DecisionTreeClassifier()

In [16]:
model.fit(iris['data'], iris['target'])

DecisionTreeClassifier()

In [17]:
import numpy as np
new_data = np.array([
    [5,3.5,1.4,0.25],
    [2,2.2,5.3,2.2],
    [1.2,5,3.2,7.6]
])
print(new_data.shape)
pred=model.predict(new_data)
print(pred)
print(iris['target_names'][pred])

(3, 4)
[0 2 1]
['setosa' 'virginica' 'versicolor']


In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    iris['data'],
    iris['target'],
    test_size=0.2,
    stratify=iris['target']
)

In [22]:
print(iris['data'].shape, iris['target'].shape)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(150, 4) (150,)
(120, 4) (120,)
(30, 4) (30,)


In [25]:
from sklearn.metrics import accuracy_score
pred_test = model.predict(X_test)
print(pred_test.shape)
result = accuracy_score(y_test, pred_test)
print("정확도:",result)

(30,)
정확도: 1.0


In [6]:
import pandas as pd
import numpy as np
data = pd.read_csv(
    'data/adult.data', 
    header=None,      # 첫번째 라인부터 데이터일 경우.
    names=cols,       # header(컬럼명) 지정
    na_values='?',    # 결측치로 읽을 값 설정.
    skipinitialspace=True # 값 앞의 공백을 제거하고 읽는다. , abc -> ' abc', 'abc'
)
data.shape
from sklearn.datasets import load_breast_cancer

data = load_breast_cancer
feature = data['data']
target = data['target']

feature.shape, target.shape

NameError: name 'cols' is not defined

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(feature, target) 

In [2]:
# 모델 학습
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [ ]:
# scaling 안한 데이터로 학습
svc1 = SVC(C=0.1, gamma=0.1, random_state=0)

svc1.fit(X_train, y_train)

pred_train1 = svc1.predict(X_train)
pred_valid1 = svc1.predict(X_valid)
pred_test1 = svc1.predict(X_test)

print(accuracy_score(y_train, pred_train1))
print(accuracy_score(y_valid, pred_valid1))
print(accuracy_score(y_test, pred_test1))

NameError: name 'X_train' is not defined